package Modelo;
// Generated 13 ene 2026, 10:42:31 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

import com.google.gson.annotations.Expose;

/**
 * Matriculaciones generated by hbm2java
 */
public class Matriculaciones implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	@Expose
	private Integer id;
	@Expose
	private Ciclos ciclos;
	@Expose
	private Users users;
	@Expose
	private byte curso;
	@Expose
	private Date fecha;

	public Matriculaciones() {
	}

	public Matriculaciones(Ciclos ciclos, Users users, byte curso, Date fecha) {
		this.ciclos = ciclos;
		this.users = users;
		this.curso = curso;
		this.fecha = fecha;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Ciclos getCiclos() {
		return this.ciclos;
	}

	public void setCiclos(Ciclos ciclos) {
		this.ciclos = ciclos;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public byte getCurso() {
		return this.curso;
	}

	public void setCurso(byte curso) {
		this.curso = curso;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
